language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  - WITH_MPI=no
#  - WITH_MPI=yes MPI4PY_VERSION=3.0.3
install:
  - python -m pip install --upgrade -r requirements.txt --no-binary setuptools_scm
#  - python setup.py sdist
#  - python -m pip install dist/*.tar.gz
  - python setup.py install
script:
  - if [ "$WITH_MPI" == "yes" ]; then python run-tests.py --no-build --verbose --full-trace; else python -m pytest --flake8 --verbose --full-trace -s; fi
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
